#!/bin/sh
SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export PATH="${HERE}/usr/bin/:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib/:${LD_LIBRARY_PATH}"
export GDK_BACKEND=wayland
export WAYLAND_DISPLAY=wayland-0
cd "${HERE}/usr/bin"
exec "${HERE}/usr/bin/xenia_launcher" "$@"
