name: xenia_launcher
description: A launcher for Xenia emulator
publish_to: 'none'
version: 1.0.1+5  # Testing workflow trigger after fixing workflow location

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  path: ^1.8.3
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0
  file_picker: ^8.0.0+1
  cached_network_image: ^3.2.3
  archive: ^3.3.7
  window_manager: ^0.3.6
  collection: ^1.17.0
  intl: ^0.18.1
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
