name: xenia_launcher
description: A Xenia Emulator Launcher
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^5.3.2
  path: ^1.8.3
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  sqflite: ^2.3.0
  path_provider: ^2.0.15
  archive: ^3.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
