name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libgtk-3-dev rpm

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Build Linux Release
      run: flutter build linux --release

    - name: Create RPM structure
      run: |
        mkdir -p rpm_build/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        cp -r build/linux/x64/release/bundle/* rpm_build/BUILD/
        
    - name: Create RPM spec file
      run: |
        cat > rpm_build/SPECS/xenia-launcher.spec << 'EOL'
        Name:           xenia-launcher
        Version:        1.0.0
        Release:        1%{?dist}
        Summary:        Xenia Game Launcher
        
        License:        MIT
        URL:            https://github.com/xenia-project/xenia-launcher
        
        BuildRequires:  gtk3-devel
        Requires:       gtk3
        
        %description
        A game launcher for the Xenia Xbox 360 emulator
        
        %prep
        # No prep needed as files are already in BUILD
        
        %install
        mkdir -p %{buildroot}/usr/bin
        mkdir -p %{buildroot}/usr/share/applications
        cp -r %{_builddir}/* %{buildroot}/usr/bin/
        
        cat > %{buildroot}/usr/share/applications/xenia-launcher.desktop << EOF
        [Desktop Entry]
        Name=Xenia Launcher
        Exec=/usr/bin/xenia_launcher
        Icon=/usr/bin/data/flutter_assets/assets/icon.png
        Type=Application
        Categories=Game;
        EOF
        
        %files
        /usr/bin/*
        /usr/share/applications/xenia-launcher.desktop
        
        %changelog
        * $(date '+%a %b %d %Y') GitHub Action <action@github.com> - 1.0.0-1
        - Initial RPM release
        EOL

    - name: Build RPM package
      run: rpmbuild --define "_topdir $(pwd)/rpm_build" -bb rpm_build/SPECS/xenia-launcher.spec

    - name: Upload RPM artifact
      uses: actions/upload-artifact@v3
      with:
        name: xenia-launcher-rpm
        path: rpm_build/RPMS/x86_64/xenia-launcher-*.rpm

    - name: Upload Linux bundle artifact
      uses: actions/upload-artifact@v3
      with:
        name: xenia-launcher-linux
        path: build/linux/x64/release/bundle
