name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get version from pubspec
      id: version
      run: |
        VERSION=$(grep 'version:' pubspec.yaml | cut -d' ' -f2 | cut -d'+' -f1)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version found: $VERSION"

    - name: Create Tag
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git tag -a v${{ steps.version.outputs.version }} -m "Release version ${{ steps.version.outputs.version }}"
        git push origin v${{ steps.version.outputs.version }}

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libgtk-3-dev rpm clang cmake pkg-config fuse dpkg-dev debhelper

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Build Linux Release
      run: flutter build linux --release

    # RPM Package Building
    - name: Create RPM structure
      run: |
        mkdir -p rpm_build/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        cp -r build/linux/x64/release/bundle/* rpm_build/BUILD/
        
    - name: Create RPM spec file
      run: |
        CHANGELOG_DATE=$(date '+%a %b %d %Y')
        cat > rpm_build/SPECS/xenia-launcher.spec << EOF
        Name:           xenia-launcher
        Version:        ${{ steps.version.outputs.version }}
        Release:        1%{?dist}
        Summary:        Xenia Game Launcher
        
        License:        MIT
        URL:            https://github.com/xenia-project/xenia-launcher
        
        BuildRequires:  gtk3-devel
        Requires:       gtk3
        
        AutoReqProv: no
        
        %description
        A game launcher for the Xenia Xbox 360 emulator
        
        %install
        mkdir -p %{buildroot}/usr/lib/xenia-launcher
        mkdir -p %{buildroot}/usr/bin
        mkdir -p %{buildroot}/usr/share/applications
        
        # Copy all files to lib directory
        cp -r %{_builddir}/* %{buildroot}/usr/lib/xenia-launcher/
        
        # Create launcher script
        cat > %{buildroot}/usr/bin/xenia-launcher << EOF2
        #!/bin/bash
        exec /usr/lib/xenia-launcher/xenia_launcher "\$@"
        EOF2
        chmod +x %{buildroot}/usr/bin/xenia-launcher
        
        # Create desktop entry
        cat > %{buildroot}/usr/share/applications/xenia-launcher.desktop << EOF2
        [Desktop Entry]
        Name=Xenia Launcher
        Exec=/usr/bin/xenia-launcher
        Icon=/usr/lib/xenia-launcher/data/flutter_assets/assets/icon.png
        Type=Application
        Categories=Game;
        EOF2
        
        %files
        %attr(755,root,root) /usr/bin/xenia-launcher
        /usr/lib/xenia-launcher
        /usr/share/applications/xenia-launcher.desktop
        
        %changelog
        * ${CHANGELOG_DATE} GitHub Action <action@github.com> - ${{ steps.version.outputs.version }}-1
        - Release version ${{ steps.version.outputs.version }}
        EOF

    - name: Build RPM package
      id: rpm_build
      run: |
        rpmbuild --define "_topdir $(pwd)/rpm_build" --nodeps -bb rpm_build/SPECS/xenia-launcher.spec
        echo "rpm_path=$(find rpm_build/RPMS -name '*.rpm' -type f)" >> $GITHUB_OUTPUT

    # DEB Package Building
    - name: Create DEB structure
      run: |
        mkdir -p deb_build/xenia-launcher_${{ steps.version.outputs.version }}-1_amd64/DEBIAN
        mkdir -p deb_build/xenia-launcher_${{ steps.version.outputs.version }}-1_amd64/usr/lib/xenia-launcher
        mkdir -p deb_build/xenia-launcher_${{ steps.version.outputs.version }}-1_amd64/usr/bin
        mkdir -p deb_build/xenia-launcher_${{ steps.version.outputs.version }}-1_amd64/usr/share/applications

    - name: Prepare DEB files
      run: |
        # Copy application files
        cp -r build/linux/x64/release/bundle/* deb_build/xenia-launcher_${{ steps.version.outputs.version }}-1_amd64/usr/lib/xenia-launcher/
        
        # Create launcher script
        cat > deb_build/xenia-launcher_${{ steps.version.outputs.version }}-1_amd64/usr/bin/xenia-launcher << EOF
        #!/bin/bash
        exec /usr/lib/xenia-launcher/xenia_launcher "\$@"
        EOF
        chmod +x deb_build/xenia-launcher_${{ steps.version.outputs.version }}-1_amd64/usr/bin/xenia-launcher
        
        # Create desktop entry
        cp AppDir/xenia-launcher.desktop deb_build/xenia-launcher_${{ steps.version.outputs.version }}-1_amd64/usr/share/applications/
        
        # Create control file
        cat > deb_build/xenia-launcher_${{ steps.version.outputs.version }}-1_amd64/DEBIAN/control << EOF
        Package: xenia-launcher
        Version: ${{ steps.version.outputs.version }}-1
        Section: games
        Priority: optional
        Architecture: amd64
        Depends: libgtk-3-0
        Maintainer: Xenia Team
        Description: Xenia Game Launcher
         A game launcher for the Xenia Xbox 360 emulator
        EOF

    - name: Build DEB package
      id: deb_build
      run: |
        dpkg-deb --build deb_build/xenia-launcher_${{ steps.version.outputs.version }}-1_amd64
        echo "deb_path=$(pwd)/deb_build/xenia-launcher_${{ steps.version.outputs.version }}-1_amd64.deb" >> $GITHUB_OUTPUT

    # AppImage Building
    - name: Prepare AppDir
      run: |
        chmod +x appimagetool
        cp -r build/linux/x64/release/bundle/* AppDir/usr/bin/
        chmod +x AppDir/AppRun

    - name: Build AppImage
      id: appimage_build
      run: |
        ARCH=x86_64 ./appimagetool AppDir/
        mv Xenia_Launcher-x86_64.AppImage xenia-launcher-${{ steps.version.outputs.version }}-x86_64.AppImage
        echo "appimage_path=$(pwd)/xenia-launcher-${{ steps.version.outputs.version }}-x86_64.AppImage" >> $GITHUB_OUTPUT

    # Upload artifacts
    - name: Upload RPM package
      uses: actions/upload-artifact@v3
      if: success() && steps.rpm_build.outputs.rpm_path != ''
      with:
        name: xenia-launcher-${{ steps.version.outputs.version }}-rpm
        path: ${{ steps.rpm_build.outputs.rpm_path }}
        if-no-files-found: error

    - name: Upload DEB package
      uses: actions/upload-artifact@v3
      if: success() && steps.deb_build.outputs.deb_path != ''
      with:
        name: xenia-launcher-${{ steps.version.outputs.version }}-deb
        path: ${{ steps.deb_build.outputs.deb_path }}
        if-no-files-found: error

    - name: Upload AppImage
      uses: actions/upload-artifact@v3
      if: success() && steps.appimage_build.outputs.appimage_path != ''
      with:
        name: xenia-launcher-${{ steps.version.outputs.version }}-appimage
        path: ${{ steps.appimage_build.outputs.appimage_path }}
        if-no-files-found: error

    # Create Release
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: Release v${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
        files: |
          ${{ steps.rpm_build.outputs.rpm_path }}
          ${{ steps.deb_build.outputs.deb_path }}
          ${{ steps.appimage_build.outputs.appimage_path }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
