name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libgtk-3-dev rpm clang cmake pkg-config

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Build Linux Release
      run: flutter build linux --release

    - name: Create RPM structure
      run: |
        mkdir -p rpm_build/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        cp -r build/linux/x64/release/bundle/* rpm_build/BUILD/
        
    - name: Create RPM spec file
      run: |
        CHANGELOG_DATE=$(date '+%a %b %d %Y')
        cat > rpm_build/SPECS/xenia-launcher.spec << EOF
        Name:           xenia-launcher
        Version:        1.0.0
        Release:        1%{?dist}
        Summary:        Xenia Game Launcher
        
        License:        MIT
        URL:            https://github.com/xenia-project/xenia-launcher
        
        BuildRequires:  gtk3-devel
        Requires:       gtk3
        
        AutoReqProv: no
        
        %description
        A game launcher for the Xenia Xbox 360 emulator
        
        %install
        mkdir -p %{buildroot}/usr/lib/xenia-launcher
        mkdir -p %{buildroot}/usr/bin
        mkdir -p %{buildroot}/usr/share/applications
        
        # Copy all files to lib directory
        cp -r %{_builddir}/* %{buildroot}/usr/lib/xenia-launcher/
        
        # Create launcher script
        cat > %{buildroot}/usr/bin/xenia-launcher << EOF2
        #!/bin/bash
        exec /usr/lib/xenia-launcher/xenia_launcher "\$@"
        EOF2
        chmod +x %{buildroot}/usr/bin/xenia-launcher
        
        # Create desktop entry
        cat > %{buildroot}/usr/share/applications/xenia-launcher.desktop << EOF2
        [Desktop Entry]
        Name=Xenia Launcher
        Exec=/usr/bin/xenia-launcher
        Icon=/usr/lib/xenia-launcher/data/flutter_assets/assets/icon.png
        Type=Application
        Categories=Game;
        EOF2
        
        %files
        %attr(755,root,root) /usr/bin/xenia-launcher
        /usr/lib/xenia-launcher
        /usr/share/applications/xenia-launcher.desktop
        
        %changelog
        * ${CHANGELOG_DATE} GitHub Action <action@github.com> - 1.0.0-1
        - Initial RPM release
        EOF

    - name: Mock RPM build environment
      run: |
        sudo ln -s /usr/include/gtk-3.0 /usr/include/gtk3
        sudo ln -s /usr/lib/x86_64-linux-gnu/gtk-3.0 /usr/lib/gtk3

    - name: Build RPM package
      run: rpmbuild --define "_topdir $(pwd)/rpm_build" --nodeps -bb rpm_build/SPECS/xenia-launcher.spec

    - name: Upload RPM artifact
      uses: actions/upload-artifact@v3
      with:
        name: xenia-launcher-rpm
        path: rpm_build/RPMS/x86_64/xenia-launcher-*.rpm

    - name: Upload Linux bundle artifact
      uses: actions/upload-artifact@v3
      with:
        name: xenia-launcher-linux
        path: build/linux/x64/release/bundle
